# Copyright (c) Alpaca Core
# SPDX-License-Identifier: MIT
#
set(AC_LOCAL_CMAKE_LIB_DIR "${CMAKE_CURRENT_LIST_DIR}")

option(AC_STANDALONE "project is standalone" ON)
option(AC_MONO_ROOT "project is a monorepo root" OFF)
option(AC_MONO_COMP "project is a monorepo component" OFF)
option(AC_DEPLOY_ROOT "project is a deploy root" OFF)
option(AC_DEPLOY_COMP "project is a deploy component" OFF)
mark_as_advanced(AC_STANDALONE AC_MONO_ROOT AC_MONO_COMP AC_DEPLOY_ROOT AC_DEPLOY_COMP)

if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    set(projectIsSubdir NO)
    set(projectIsRoot YES)
    set(projectIsStandalone ${AC_STANDALONE})
    set(projectIsMonoRoot ${AC_MONO_ROOT})
    set(projectIsMonoComponent ${AC_MONO_COMP})
    set(projectIsDeployRoot ${AC_DEPLOY_ROOT})
    set(projectIsDeployComponent ${AC_DEPLOY_COMP})
    include(setup_ac_local_prj_root)
else()
    set(projectIsSubdir YES)
    set(projectIsRoot NO)
    set(projectIsStandalone NO)
    set(projectIsMonoRoot NO)
    set(projectIsMonoComponent NO)
    set(projectIsDeployRoot NO)
    set(projectIsDeployComponent NO)
endif()

if(projectIsRoot OR AC_MONO_ROOT)
    set(testsDefault ON)
    set(toolsDefault ON)
    if(projectIsDeployRoot OR projectIsDeployComponent)
        set(examplesDefault OFF)
    else()
        set(examplesDefault ON)
    endif()
    set(pluginDefault ON)
else()
    set(testsDefault OFF)
    set(toolsDefault OFF)
    set(examplesDefault OFF)
    set(pluginDefault OFF)
endif()
